### ISSUE TITLE
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with: 	status = StatusCode.OUT_OF_RANGE

### ISSUE THREAD

**Issue by Mohit0888** [twilio/media-streams#47]
Exception in thread Thread-4:
Traceback (most recent call last):
  File "C:\Users\jai\AppData\Local\Programs\Python\Python35-32\chat35\lib\site-packages\google\api_core\grpc_helpers.py", line 96, in next
    return six.next(self._wrapped)
  File "C:\Users\jai\AppData\Local\Programs\Python\Python35-32\chat35\lib\site-packages\grpc\_channel.py", line 416, in __next__
    return self._next()
  File "C:\Users\jai\AppData\Local\Programs\Python\Python35-32\chat35\lib\site-packages\grpc\_channel.py", line 689, in _next
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.OUT_OF_RANGE
	details = "Audio Timeout Error: Long duration elapsed without audio. Audio should be sent close to real time."
	debug_error_string = "{"created":"@1588336851.014000000","description":"Error received from peer ipv4:172.217.31.10:443","file":"src/core/lib/surface/call.cc","file_line":1056,"grpc_message":"Audio Timeout Error: Long duration elapsed without audio. Audio should be sent close to real time.","grpc_status":11}"
>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\jai\AppData\Local\Programs\Python\Python35-32\lib\threading.py", line 923, in _bootstrap_inner
    self.run()
  File "C:\Users\jai\AppData\Local\Programs\Python\Python35-32\lib\threading.py", line 871, in run
    self._target(*self._args, **self._kwargs)
  File "C:\GitDemo\mediastreams-consume-websockets-flask-master\SpeechClientBridge.py", line 36, in process_responses_loop
    for response in responses:
  File "C:\Users\jai\AppData\Local\Programs\Python\Python35-32\chat35\lib\site-packages\google\api_core\grpc_helpers.py", line 99, in next
    six.raise_from(exceptions.from_grpc_error(exc), exc)
  File "<string>", line 3, in raise_from
google.api_core.exceptions.OutOfRange: 400 Audio Timeout Error: Long duration elapsed without audio. Audio should be sent close to real time.

**Comment by Mohit0888** [comment]
having this issue when receiving the audio stream on my web socket..

**Comment by yeinel** [comment]
Hi @Mohit0888 , do you have any update about this issue ?

**Comment by irishguy** [comment]
I'm also having this issue.
